// Static Storybook metadata for framework wrapper targets.
// Keep this aligned with the wrapper APIs exposed by @cobalt/react, @cobalt/vue, and @cobalt/angular.

export type CobaltControlType = 'boolean' | 'number' | 'object' | 'select' | 'text';

export type CobaltApiProp = {
  name: string;
  attribute: string;
  type: string;
  control: CobaltControlType;
  defaultValue?: unknown;
  options?: readonly string[];
  description?: string;
};

export type CobaltApiSlot = {
  name: string;
  argName: string;
  label: string;
  defaultValue?: string;
  description?: string;
};

export type CobaltApiEvent = {
  name: string;
  argName: string;
  angularName: string;
  description?: string;
};

export type CobaltComponentMetadata = {
  id: string;
  title: string;
  tagName: string;
  importName: string;
  componentPath: string;
  props: readonly CobaltApiProp[];
  slots: readonly CobaltApiSlot[];
  events: readonly CobaltApiEvent[];
  playgroundDefaults: Record<string, unknown>;
};

export const wrapperStoryMetadata = {
  button: {
    id: 'button',
    title: 'Button',
    tagName: 'co-button',
    importName: 'CoButton',
    componentPath: 'button',
    props: [
      {
        name: 'variant',
        attribute: 'variant',
        type: 'ButtonVariant',
        control: 'select',
        defaultValue: 'primary',
        options: ['primary', 'secondary', 'danger', 'success', 'ghost'],
        description: 'The button variant.',
      },
      {
        name: 'size',
        attribute: 'size',
        type: 'ButtonSize',
        control: 'select',
        defaultValue: 'md',
        options: ['sm', 'md', 'lg', 'xl'],
        description: 'The button size.',
      },
      {
        name: 'disabled',
        attribute: 'disabled',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
      },
      {
        name: 'loading',
        attribute: 'loading',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
        description: 'Shows a loading spinner.',
      },
      {
        name: 'type',
        attribute: 'type',
        type: "'submit' | 'reset' | 'button'",
        control: 'select',
        defaultValue: 'button',
        options: ['submit', 'reset', 'button'],
      },
      {
        name: 'href',
        attribute: 'href',
        type: 'string | undefined',
        control: 'text',
        description: 'An optional href to render the button as a link.',
      },
      {
        name: 'target',
        attribute: 'target',
        type: "'_blank' | '_self' | '_parent' | '_top' | undefined",
        control: 'select',
        options: ['_blank', '_self', '_parent', '_top'],
        description: 'Where to open the link (when href is set).',
      },
    ],
    slots: [
      {
        name: '',
        argName: 'slotDefault',
        label: 'Content',
        defaultValue: 'Save changes',
        description: 'Default slot for button content',
      },
      {
        name: 'prefix',
        argName: 'slotPrefix',
        label: 'Prefix icon',
        defaultValue: 'add',
        description: 'Content before the label',
      },
      {
        name: 'suffix',
        argName: 'slotSuffix',
        label: 'Suffix icon',
        defaultValue: '',
        description: 'Content after the label',
      },
    ],
    events: [
      {
        name: 'co-focus',
        argName: 'onCoFocus',
        angularName: 'coFocus',
        description: 'Emitted when the button gains focus',
      },
      {
        name: 'co-blur',
        argName: 'onCoBlur',
        angularName: 'coBlur',
        description: 'Emitted when the button loses focus',
      },
    ],
    playgroundDefaults: {
      slotDefault: 'Save changes',
    },
  },
  buttonIcon: {
    id: 'buttonIcon',
    title: 'Button Icon',
    tagName: 'co-button-icon',
    importName: 'CoButtonIcon',
    componentPath: 'button-icon',
    props: [
      {
        name: 'name',
        attribute: 'name',
        type: 'string',
        control: 'select',
        defaultValue: '',
        options: [
          'home',
          'search',
          'settings',
          'person',
          'add',
          'delete',
          'edit',
          'info',
          'warning',
          'check-circle',
          'arrow-forward',
          'open-in-new',
          'star',
          'favorite',
          'notifications',
          'progress-activity',
        ],
        description: 'The icon name passed to the internal co-icon.',
      },
      {
        name: 'variant',
        attribute: 'variant',
        type: 'ButtonVariant',
        control: 'select',
        defaultValue: 'primary',
        options: ['primary', 'secondary', 'danger', 'success', 'ghost'],
        description: 'The button variant.',
      },
      {
        name: 'size',
        attribute: 'size',
        type: 'ButtonSize',
        control: 'select',
        defaultValue: 'md',
        options: ['sm', 'md', 'lg', 'xl'],
        description: 'The button size.',
      },
      {
        name: 'label',
        attribute: 'label',
        type: 'string | undefined',
        control: 'text',
        description: 'Optional visible text label.',
      },
      {
        name: 'labelPosition',
        attribute: 'label-position',
        type: 'ButtonIconLabelPosition',
        control: 'select',
        defaultValue: 'bottom',
        options: ['top', 'bottom'],
        description: 'Position of the label relative to the icon.',
      },
      {
        name: 'circle',
        attribute: 'circle',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
        description: 'Renders the button as a circle. Label is ignored when set.',
      },
      {
        name: 'disabled',
        attribute: 'disabled',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
      },
    ],
    slots: [],
    events: [
      {
        name: 'co-focus',
        argName: 'onCoFocus',
        angularName: 'coFocus',
        description: 'Emitted when the button gains focus',
      },
      {
        name: 'co-blur',
        argName: 'onCoBlur',
        angularName: 'coBlur',
        description: 'Emitted when the button loses focus',
      },
    ],
    playgroundDefaults: {
      name: 'star',
      label: 'Favorite',
    },
  },
  checkbox: {
    id: 'checkbox',
    title: 'Checkbox',
    tagName: 'co-checkbox',
    importName: 'CoCheckbox',
    componentPath: 'checkbox',
    props: [
      {
        name: 'value',
        attribute: 'value',
        type: 'string',
        control: 'text',
        defaultValue: '',
        description: "String value alias mapped to Lion's choiceValue.",
      },
      {
        name: 'checked',
        attribute: 'checked',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
      },
      {
        name: 'disabled',
        attribute: 'disabled',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
      },
    ],
    slots: [
      {
        name: '',
        argName: 'slotDefault',
        label: 'Label',
        defaultValue: 'Accept terms',
        description: 'Checkbox label content',
      },
    ],
    events: [],
    playgroundDefaults: {
      value: 'accept',
    },
  },
  checkboxGroup: {
    id: 'checkboxGroup',
    title: 'Checkbox Group',
    tagName: 'co-checkbox-group',
    importName: 'CoCheckboxGroup',
    componentPath: 'checkbox-group',
    props: [
      {
        name: 'name',
        attribute: 'name',
        type: 'string',
        control: 'text',
        defaultValue: '',
      },
      {
        name: 'disabled',
        attribute: 'disabled',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
      },
      {
        name: 'required',
        attribute: 'required',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
        description: 'Marks the checkbox group as required for validation.',
      },
    ],
    slots: [
      {
        name: 'label',
        argName: 'slotLabel',
        label: 'Label',
        defaultValue: 'Preferences',
        description: 'Label content for the checkbox group',
      },
      {
        name: 'help-text',
        argName: 'slotHelpText',
        label: 'Help text',
        defaultValue: 'Choose all that apply.',
        description: 'Help text shown below the label',
      },
      {
        name: 'feedback',
        argName: 'slotFeedback',
        label: 'Feedback',
        defaultValue: '',
        description: 'Validation feedback rendered by Lion',
      },
    ],
    events: [
      {
        name: 'co-change',
        argName: 'onCoChange',
        angularName: 'coChange',
        description: 'Emitted when the selected checkboxes change',
      },
    ],
    playgroundDefaults: {
      name: 'preferences',
      selectedValues: 'email,product',
      optionItems: [
        {
          value: 'email',
          label: 'Email updates',
        },
        {
          value: 'product',
          label: 'Product news',
        },
        {
          value: 'research',
          label: 'Research invitations',
        },
      ],
    },
  },
  checkboxIndeterminate: {
    id: 'checkboxIndeterminate',
    title: 'Checkbox Indeterminate',
    tagName: 'co-checkbox-indeterminate',
    importName: 'CoCheckboxIndeterminate',
    componentPath: 'checkbox-indeterminate',
    props: [
      {
        name: 'value',
        attribute: 'value',
        type: 'string',
        control: 'text',
        defaultValue: '',
        description: "String value alias mapped to Lion's choiceValue.",
      },
      {
        name: 'checked',
        attribute: 'checked',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
      },
      {
        name: 'indeterminate',
        attribute: 'indeterminate',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
      },
      {
        name: 'mixedState',
        attribute: 'mixed-state',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
      },
      {
        name: 'disabled',
        attribute: 'disabled',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
      },
    ],
    slots: [
      {
        name: 'label',
        argName: 'slotLabel',
        label: 'Label',
        defaultValue: 'Notifications',
        description: 'Checkbox label content',
      },
    ],
    events: [],
    playgroundDefaults: {
      value: 'notifications',
      indeterminate: true,
      optionItems: [
        {
          value: 'email',
          label: 'Email',
        },
        {
          value: 'sms',
          label: 'SMS',
        },
        {
          value: 'push',
          label: 'Push',
        },
      ],
      selectedValues: 'email',
    },
  },
  icon: {
    id: 'icon',
    title: 'Icon',
    tagName: 'co-icon',
    importName: 'CoIcon',
    componentPath: 'icon',
    props: [
      {
        name: 'name',
        attribute: 'name',
        type: 'string',
        control: 'select',
        defaultValue: '',
        options: [
          'home',
          'search',
          'settings',
          'person',
          'add',
          'delete',
          'edit',
          'info',
          'warning',
          'check-circle',
          'arrow-forward',
          'open-in-new',
          'star',
          'favorite',
          'notifications',
          'progress-activity',
        ],
        description: 'The icon name in kebab-case (e.g. "arrow-forward").',
      },
      {
        name: 'size',
        attribute: 'size',
        type: 'IconSize',
        control: 'select',
        defaultValue: 'md',
        options: ['xs', 'sm', 'md', 'lg', 'xl'],
        description: 'The icon size.',
      },
      {
        name: 'fill',
        attribute: 'fill',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
        description: 'Whether to use the filled version of the icon.',
      },
      {
        name: 'animated',
        attribute: 'animated',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
        description: 'Whether to use the animated variant of the icon (if available).',
      },
      {
        name: 'label',
        attribute: 'label',
        type: 'string | undefined',
        control: 'text',
        description: 'Accessible label. When set, the icon is treated as informative (role="img").',
      },
    ],
    slots: [],
    events: [],
    playgroundDefaults: {
      name: 'home',
      label: 'Home',
    },
  },
  input: {
    id: 'input',
    title: 'Input',
    tagName: 'co-input',
    importName: 'CoInput',
    componentPath: 'input',
    props: [
      {
        name: 'size',
        attribute: 'size',
        type: 'InputSize',
        control: 'select',
        defaultValue: 'md',
        options: ['sm', 'md', 'lg', 'xl'],
        description: 'The input size.',
      },
      {
        name: 'danger',
        attribute: 'danger',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
        description: 'Applies danger styling without changing validation state.',
      },
      {
        name: 'disabled',
        attribute: 'disabled',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
      },
      {
        name: 'readOnly',
        attribute: 'read-only',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
      },
      {
        name: 'required',
        attribute: 'required',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
      },
      {
        name: 'label',
        attribute: 'label',
        type: 'string | undefined',
        control: 'text',
      },
      {
        name: 'helpText',
        attribute: 'help-text',
        type: 'string | undefined',
        control: 'text',
      },
      {
        name: 'name',
        attribute: 'name',
        type: 'string | undefined',
        control: 'text',
      },
      {
        name: 'type',
        attribute: 'type',
        type: 'string',
        control: 'select',
        defaultValue: 'text',
        options: ['text', 'email', 'password', 'search', 'tel', 'url'],
      },
      {
        name: 'placeholder',
        attribute: 'placeholder',
        type: 'string | undefined',
        control: 'text',
      },
      {
        name: 'value',
        attribute: 'value',
        type: 'string | undefined',
        control: 'text',
      },
      {
        name: 'modelValue',
        attribute: 'model-value',
        type: 'unknown',
        control: 'object',
      },
    ],
    slots: [
      {
        name: 'prefix',
        argName: 'slotPrefix',
        label: 'Prefix icon',
        defaultValue: 'search',
        description: 'Content before the input value',
      },
      {
        name: 'suffix',
        argName: 'slotSuffix',
        label: 'Suffix icon',
        defaultValue: '',
        description: 'Content after the input value',
      },
      {
        name: 'feedback',
        argName: 'slotFeedback',
        label: 'Feedback',
        defaultValue: '',
        description: 'Validation feedback rendered by Lion',
      },
    ],
    events: [
      {
        name: 'co-focus',
        argName: 'onCoFocus',
        angularName: 'coFocus',
        description: 'Emitted when the native input gains focus',
      },
      {
        name: 'co-blur',
        argName: 'onCoBlur',
        angularName: 'coBlur',
        description: 'Emitted when the native input loses focus',
      },
      {
        name: 'co-input',
        argName: 'onCoInput',
        angularName: 'coInput',
        description: 'Emitted when the native input value changes during editing',
      },
      {
        name: 'co-change',
        argName: 'onCoChange',
        angularName: 'coChange',
        description: 'Emitted when the native input value is committed',
      },
    ],
    playgroundDefaults: {
      label: 'Email',
      helpText: 'Use your work email.',
      name: 'email',
      placeholder: 'name@example.com',
      value: '',
    },
  },
  textarea: {
    id: 'textarea',
    title: 'Textarea',
    tagName: 'co-textarea',
    importName: 'CoTextarea',
    componentPath: 'textarea',
    props: [
      {
        name: 'size',
        attribute: 'size',
        type: 'TextareaSize',
        control: 'select',
        defaultValue: 'md',
        options: ['sm', 'md', 'lg', 'xl'],
        description: 'The textarea size.',
      },
      {
        name: 'resize',
        attribute: 'resize',
        type: 'TextareaResize',
        control: 'select',
        defaultValue: 'auto',
        options: ['auto', 'none', 'vertical'],
        description: 'Controls automatic or manual resizing behavior.',
      },
      {
        name: 'danger',
        attribute: 'danger',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
        description: 'Applies danger styling without changing validation state.',
      },
      {
        name: 'disabled',
        attribute: 'disabled',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
      },
      {
        name: 'readOnly',
        attribute: 'read-only',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
      },
      {
        name: 'required',
        attribute: 'required',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
      },
      {
        name: 'label',
        attribute: 'label',
        type: 'string | undefined',
        control: 'text',
      },
      {
        name: 'helpText',
        attribute: 'help-text',
        type: 'string | undefined',
        control: 'text',
      },
      {
        name: 'name',
        attribute: 'name',
        type: 'string | undefined',
        control: 'text',
      },
      {
        name: 'placeholder',
        attribute: 'placeholder',
        type: 'string | undefined',
        control: 'text',
      },
      {
        name: 'value',
        attribute: 'value',
        type: 'string | undefined',
        control: 'text',
      },
      {
        name: 'modelValue',
        attribute: 'model-value',
        type: 'unknown',
        control: 'object',
      },
      {
        name: 'rows',
        attribute: 'rows',
        type: 'number | undefined',
        control: 'number',
      },
      {
        name: 'maxRows',
        attribute: 'max-rows',
        type: 'number | undefined',
        control: 'number',
      },
      {
        name: 'maxLength',
        attribute: 'maxlength',
        type: 'number | undefined',
        control: 'number',
        description: 'Maximum number of characters allowed by the native textarea.',
      },
      {
        name: 'minLength',
        attribute: 'minlength',
        type: 'number | undefined',
        control: 'number',
        description: 'Minimum number of characters expected by the native textarea.',
      },
    ],
    slots: [
      {
        name: 'prefix',
        argName: 'slotPrefix',
        label: 'Prefix icon',
        defaultValue: '',
        description: 'Content before the textarea value',
      },
      {
        name: 'suffix',
        argName: 'slotSuffix',
        label: 'Suffix icon',
        defaultValue: '',
        description: 'Content after the textarea value',
      },
      {
        name: 'feedback',
        argName: 'slotFeedback',
        label: 'Feedback',
        defaultValue: '',
        description: 'Validation feedback rendered by Lion',
      },
    ],
    events: [
      {
        name: 'co-focus',
        argName: 'onCoFocus',
        angularName: 'coFocus',
        description: 'Emitted when the native textarea gains focus',
      },
      {
        name: 'co-blur',
        argName: 'onCoBlur',
        angularName: 'coBlur',
        description: 'Emitted when the native textarea loses focus',
      },
      {
        name: 'co-input',
        argName: 'onCoInput',
        angularName: 'coInput',
        description: 'Emitted when the native textarea value changes during editing',
      },
      {
        name: 'co-change',
        argName: 'onCoChange',
        angularName: 'coChange',
        description: 'Emitted when the native textarea value is committed',
      },
    ],
    playgroundDefaults: {
      label: 'Comment',
      helpText: 'Keep it short and specific.',
      name: 'comment',
      placeholder: 'Write a note',
      rows: 3,
      maxRows: 6,
      maxLength: 120,
      value: '',
    },
  },
  option: {
    id: 'option',
    title: 'Option',
    tagName: 'co-option',
    importName: 'CoOption',
    componentPath: 'option',
    props: [
      {
        name: 'value',
        attribute: 'value',
        type: 'string | undefined',
        control: 'text',
        description: "String value alias mapped to Lion's choiceValue.",
      },
      {
        name: 'choiceValue',
        attribute: 'choice-value',
        type: 'unknown',
        control: 'object',
      },
      {
        name: 'checked',
        attribute: 'checked',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
      },
      {
        name: 'disabled',
        attribute: 'disabled',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
      },
      {
        name: 'active',
        attribute: 'active',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
      },
    ],
    slots: [
      {
        name: '',
        argName: 'slotDefault',
        label: 'Content',
        defaultValue: 'Apple',
        description: 'Option label content',
      },
      {
        name: 'indicator-icon',
        argName: 'slotIndicatorIcon',
        label: 'Indicator icon',
        defaultValue: 'check-circle',
      },
      {
        name: 'indicator',
        argName: 'slotIndicator',
        label: 'Indicator',
        defaultValue: '',
      },
    ],
    events: [],
    playgroundDefaults: {
      value: 'apple',
      checked: true,
    },
  },
  radio: {
    id: 'radio',
    title: 'Radio',
    tagName: 'co-radio',
    importName: 'CoRadio',
    componentPath: 'radio',
    props: [
      {
        name: 'value',
        attribute: 'value',
        type: 'string',
        control: 'text',
        defaultValue: '',
        description: "String value alias mapped to Lion's choiceValue.",
      },
      {
        name: 'checked',
        attribute: 'checked',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
      },
      {
        name: 'disabled',
        attribute: 'disabled',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
      },
    ],
    slots: [
      {
        name: '',
        argName: 'slotDefault',
        label: 'Label',
        defaultValue: 'Standard',
        description: 'Radio label content',
      },
    ],
    events: [],
    playgroundDefaults: {
      value: 'standard',
      checked: true,
    },
  },
  radioGroup: {
    id: 'radioGroup',
    title: 'Radio Group',
    tagName: 'co-radio-group',
    importName: 'CoRadioGroup',
    componentPath: 'radio-group',
    props: [
      {
        name: 'name',
        attribute: 'name',
        type: 'string',
        control: 'text',
        defaultValue: '',
      },
      {
        name: 'disabled',
        attribute: 'disabled',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
      },
      {
        name: 'required',
        attribute: 'required',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
        description: 'Marks the radio group as required for validation.',
      },
    ],
    slots: [
      {
        name: 'label',
        argName: 'slotLabel',
        label: 'Label',
        defaultValue: 'Plan',
        description: 'Label content for the radio group',
      },
      {
        name: 'help-text',
        argName: 'slotHelpText',
        label: 'Help text',
        defaultValue: 'Choose one option.',
        description: 'Help text shown below the label',
      },
      {
        name: 'feedback',
        argName: 'slotFeedback',
        label: 'Feedback',
        defaultValue: '',
        description: 'Validation feedback rendered by Lion',
      },
    ],
    events: [
      {
        name: 'co-change',
        argName: 'onCoChange',
        angularName: 'coChange',
        description: 'Emitted when the selected radio changes',
      },
    ],
    playgroundDefaults: {
      name: 'plan',
      selectedValues: 'team',
      optionItems: [
        {
          value: 'starter',
          label: 'Starter',
        },
        {
          value: 'team',
          label: 'Team',
        },
        {
          value: 'enterprise',
          label: 'Enterprise',
        },
      ],
    },
  },
  listbox: {
    id: 'listbox',
    title: 'Listbox',
    tagName: 'co-listbox',
    importName: 'CoListbox',
    componentPath: 'listbox',
    props: [
      {
        name: 'label',
        attribute: 'label',
        type: 'string | undefined',
        control: 'text',
      },
      {
        name: 'helpText',
        attribute: 'help-text',
        type: 'string | undefined',
        control: 'text',
      },
      {
        name: 'name',
        attribute: 'name',
        type: 'string | undefined',
        control: 'text',
      },
      {
        name: 'disabled',
        attribute: 'disabled',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
      },
      {
        name: 'required',
        attribute: 'required',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
        description: 'Marks the listbox as required for validation and assistive technology.',
      },
      {
        name: 'multipleChoice',
        attribute: 'multiple-choice',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
        description: 'Allows multiple options to be selected.',
      },
      {
        name: 'orientation',
        attribute: 'orientation',
        type: 'ListboxOrientation',
        control: 'select',
        defaultValue: 'vertical',
        options: ['vertical', 'horizontal'],
        description: 'Informs screen readers and controls arrow-key direction.',
      },
      {
        name: 'selectionFollowsFocus',
        attribute: 'selection-follows-focus',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
        description: 'Selects the active option while arrowing through options.',
      },
      {
        name: 'rotateKeyboardNavigation',
        attribute: 'rotate-keyboard-navigation',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
        description: 'Allows keyboard navigation to wrap from last to first option.',
      },
      {
        name: 'hasNoDefaultSelected',
        attribute: 'has-no-default-selected',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
        description: 'Prevents Lion from selecting a default option on initialization.',
      },
      {
        name: 'modelValue',
        attribute: 'model-value',
        type: 'unknown',
        control: 'object',
      },
    ],
    slots: [
      {
        name: 'feedback',
        argName: 'slotFeedback',
        label: 'Feedback',
        defaultValue: '',
        description: 'Validation feedback rendered by Lion',
      },
    ],
    events: [
      {
        name: 'co-change',
        argName: 'onCoChange',
        angularName: 'coChange',
        description: 'Emitted when the selected option value changes',
      },
    ],
    playgroundDefaults: {
      label: 'Fruit',
      helpText: 'Choose one option.',
      name: 'fruit',
      selectedValues: 'apple',
      optionItems: [
        {
          value: 'apple',
          label: 'Apple',
        },
        {
          value: 'banana',
          label: 'Banana',
        },
        {
          value: 'carrot',
          label: 'Carrot',
        },
        {
          value: 'date',
          label: 'Date',
        },
      ],
    },
  },
  select: {
    id: 'select',
    title: 'Select',
    tagName: 'co-select',
    importName: 'CoSelect',
    componentPath: 'select',
    props: [
      {
        name: 'size',
        attribute: 'size',
        type: 'SelectSize',
        control: 'select',
        defaultValue: 'md',
        options: ['sm', 'md', 'lg', 'xl'],
        description: 'Controls field height, padding, and font size.',
      },
      {
        name: 'danger',
        attribute: 'danger',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
        description: 'Applies danger styling without changing validation state.',
      },
      {
        name: 'disabled',
        attribute: 'disabled',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
      },
      {
        name: 'readOnly',
        attribute: 'read-only',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
      },
      {
        name: 'required',
        attribute: 'required',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
        description: 'Marks the select as required for validation.',
      },
      {
        name: 'hasNoDefaultSelected',
        attribute: 'has-no-default-selected',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
      },
    ],
    slots: [
      {
        name: 'label',
        argName: 'slotLabel',
        label: 'Label',
        defaultValue: 'Fruit',
        description: 'Label content for the select',
      },
      {
        name: 'help-text',
        argName: 'slotHelpText',
        label: 'Help text',
        defaultValue: 'Choose one option.',
        description: 'Help text shown below the label',
      },
      {
        name: 'feedback',
        argName: 'slotFeedback',
        label: 'Feedback',
        defaultValue: '',
        description: 'Validation feedback rendered by Lion',
      },
    ],
    events: [
      {
        name: 'co-change',
        argName: 'onCoChange',
        angularName: 'coChange',
        description: 'Emitted when the selected option changes',
      },
      {
        name: 'co-focus',
        argName: 'onCoFocus',
        angularName: 'coFocus',
        description: 'Emitted when the select gains focus',
      },
      {
        name: 'co-blur',
        argName: 'onCoBlur',
        angularName: 'coBlur',
        description: 'Emitted when the select loses focus',
      },
    ],
    playgroundDefaults: {
      selectedValues: 'apple',
      optionItems: [
        {
          value: 'apple',
          label: 'Apple',
        },
        {
          value: 'banana',
          label: 'Banana',
        },
        {
          value: 'carrot',
          label: 'Carrot',
        },
        {
          value: 'date',
          label: 'Date',
        },
      ],
    },
  },
  combobox: {
    id: 'combobox',
    title: 'Combobox',
    tagName: 'co-combobox',
    importName: 'CoCombobox',
    componentPath: 'combobox',
    props: [
      {
        name: 'size',
        attribute: 'size',
        type: 'ComboboxSize',
        control: 'select',
        defaultValue: 'md',
        options: ['sm', 'md', 'lg', 'xl'],
        description: 'Controls field height, padding, and font size.',
      },
      {
        name: 'danger',
        attribute: 'danger',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
        description: 'Applies danger styling without changing validation state.',
      },
      {
        name: 'disabled',
        attribute: 'disabled',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
      },
      {
        name: 'readOnly',
        attribute: 'read-only',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
      },
      {
        name: 'required',
        attribute: 'required',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
        description: 'Marks the combobox as required for validation and assistive technology.',
      },
      {
        name: 'label',
        attribute: 'label',
        type: 'string | undefined',
        control: 'text',
      },
      {
        name: 'helpText',
        attribute: 'help-text',
        type: 'string | undefined',
        control: 'text',
      },
      {
        name: 'name',
        attribute: 'name',
        type: 'string | undefined',
        control: 'text',
      },
      {
        name: 'value',
        attribute: 'value',
        type: 'string | undefined',
        control: 'text',
      },
      {
        name: 'modelValue',
        attribute: 'model-value',
        type: 'unknown',
        control: 'object',
      },
      {
        name: 'autocomplete',
        attribute: 'autocomplete',
        type: 'ComboboxAutocomplete',
        control: 'select',
        defaultValue: 'both',
        options: ['none', 'list', 'inline', 'both'],
        description: 'Controls Lion combobox autocomplete behavior.',
      },
      {
        name: 'matchMode',
        attribute: 'match-mode',
        type: 'ComboboxMatchMode',
        control: 'select',
        defaultValue: 'all',
        options: ['begin', 'all'],
        description:
          'Controls whether filtering matches from the beginning or anywhere in options.',
      },
      {
        name: 'showAllOnEmpty',
        attribute: 'show-all-on-empty',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
        description: 'Shows all options when the textbox is empty and the overlay is open.',
      },
      {
        name: 'selectionFollowsFocus',
        attribute: 'selection-follows-focus',
        type: 'boolean',
        control: 'boolean',
        defaultValue: true,
        description: 'Selects the active option while arrowing through options.',
      },
      {
        name: 'rotateKeyboardNavigation',
        attribute: 'rotate-keyboard-navigation',
        type: 'boolean',
        control: 'boolean',
        defaultValue: true,
        description: 'Allows keyboard navigation to wrap from last to first option.',
      },
      {
        name: 'hasNoDefaultSelected',
        attribute: 'has-no-default-selected',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
        description: 'Prevents Lion from selecting a default option on initialization.',
      },
      {
        name: 'multiple',
        attribute: 'multiple',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
        description: "Cobalt alias for Lion's multipleChoice property.",
      },
      {
        name: 'multipleChoice',
        attribute: 'multiple-choice',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
        description: 'Allows multiple options to be selected.',
      },
      {
        name: 'allowCustomChoice',
        attribute: 'allow-custom-choice',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
        description: 'Allows values that do not match an existing option.',
      },
      {
        name: 'matchError',
        attribute: 'match-error',
        type: 'string',
        control: 'text',
        defaultValue: '',
        description: 'Custom error message shown when the entered value does not match any option.',
      },
      {
        name: 'requireOptionMatch',
        attribute: 'require-option-match',
        type: 'boolean | undefined',
        control: 'boolean',
        description: 'Lion-compatible inverse of allowCustomChoice.',
      },
    ],
    slots: [
      {
        name: 'prefix',
        argName: 'slotPrefix',
        label: 'Prefix icon',
        defaultValue: 'search',
        description: 'Content before the combobox value',
      },
      {
        name: 'suffix',
        argName: 'slotSuffix',
        label: 'Suffix icon',
        defaultValue: '',
        description: 'Content after the combobox value',
      },
      {
        name: 'feedback',
        argName: 'slotFeedback',
        label: 'Feedback',
        defaultValue: '',
        description: 'Validation feedback rendered by Lion',
      },
    ],
    events: [
      {
        name: 'co-focus',
        argName: 'onCoFocus',
        angularName: 'coFocus',
        description: 'Emitted when the native combobox input gains focus',
      },
      {
        name: 'co-blur',
        argName: 'onCoBlur',
        angularName: 'coBlur',
        description: 'Emitted when the native combobox input loses focus',
      },
      {
        name: 'co-input',
        argName: 'onCoInput',
        angularName: 'coInput',
        description: 'Emitted when the native combobox input value changes during editing',
      },
      {
        name: 'co-change',
        argName: 'onCoChange',
        angularName: 'coChange',
        description: 'Emitted when the combobox model value changes',
      },
    ],
    playgroundDefaults: {
      label: 'Fruit',
      helpText: 'Type to filter options.',
      name: 'fruit',
      showAllOnEmpty: true,
      selectedValues: 'apple',
      optionItems: [
        {
          value: 'apple',
          label: 'Apple',
        },
        {
          value: 'banana',
          label: 'Banana',
        },
        {
          value: 'carrot',
          label: 'Carrot',
        },
        {
          value: 'date',
          label: 'Date',
        },
      ],
    },
  },
  form: {
    id: 'form',
    title: 'Form',
    tagName: 'co-form',
    importName: 'CoForm',
    componentPath: 'form',
    props: [
      {
        name: 'disabled',
        attribute: 'disabled',
        type: 'boolean',
        control: 'boolean',
        defaultValue: false,
        description: 'Whether the form is disabled. Cascades to all child form elements.',
      },
      {
        name: 'label',
        attribute: 'label',
        type: 'string | undefined',
        control: 'text',
      },
      {
        name: 'helpText',
        attribute: 'help-text',
        type: 'string | undefined',
        control: 'text',
      },
      {
        name: 'name',
        attribute: 'name',
        type: 'string | undefined',
        control: 'text',
      },
    ],
    slots: [
      {
        name: 'feedback',
        argName: 'slotFeedback',
        label: 'Feedback',
        defaultValue: '',
        description: 'Validation feedback rendered by Lion',
      },
    ],
    events: [
      {
        name: 'co-submit',
        argName: 'onCoSubmit',
        angularName: 'coSubmit',
        description: 'Emitted when the form is submitted (after validation)',
      },
      {
        name: 'co-reset',
        argName: 'onCoReset',
        angularName: 'coReset',
        description: 'Emitted when the form is reset',
      },
    ],
    playgroundDefaults: {
      label: 'Feedback',
      helpText: 'Share enough detail to act on.',
      name: 'feedback',
    },
  },
} as const satisfies Record<string, CobaltComponentMetadata>;
