// Generated by packages/storybook-fixtures/scripts/generate-stories.js.
// Do not edit directly. Run `pnpm storybook:stories:generate` after Storybook component changes.

import '@cobalt/components/app-shell';
import '@cobalt/components/banner';
import '@cobalt/components/button';
import '@cobalt/components/card';
import '@cobalt/components/icon';
import '@cobalt/components/nav-drawer';
import '@cobalt/components/nav-drawer-item';
import '@cobalt/components/nav-header-bar';
import '@cobalt/components/nav-rail-bar';
import '@cobalt/components/nav-rail-item';
import '@cobalt/components/nav-separator';
import { createWebPlaygroundStory, createWebScenarioStory } from './playground.js';

export default {
  title: 'Components/App Shell',
};

const componentId = 'appShell' as const;

export const Playground = createWebPlaygroundStory(componentId);

export const Overview = createWebScenarioStory(componentId, 'overview');

export const DrawerOpen = createWebScenarioStory(componentId, 'drawerOpen');
