// Generated by packages/storybook-fixtures/scripts/generate-stories.js.
// Do not edit directly. Run `pnpm storybook:stories:generate` after Storybook component changes.

import '@cobalt/components/banner';
import { createWebPlaygroundStory, createWebScenarioStory } from './playground.js';

export default {
  title: 'Components/Banner',
};

const componentId = 'banner' as const;

export const Playground = createWebPlaygroundStory(componentId);

export const Overview = createWebScenarioStory(componentId, 'overview');

export const LongContent = createWebScenarioStory(componentId, 'longContent');
