// Generated by packages/storybook-fixtures/scripts/generate-stories.js.
// Do not edit directly. Run `pnpm storybook:stories:generate` after Storybook component changes.

import '@cobalt/components/checkbox';
import { createWebPlaygroundStory, createWebStarterOverviewStory } from './playground.js';

export default {
  title: 'Components/Checkbox',
};

const componentId = 'checkbox' as const;

export const Playground = createWebPlaygroundStory(componentId);

export const Overview = createWebStarterOverviewStory(componentId);
