// Generated by packages/storybook-fixtures/scripts/generate-stories.js.
// Do not edit directly. Run `pnpm storybook:stories:generate` after Storybook component changes.

import '@cobalt/components/label';
import '@cobalt/components/icon';
import { createWebPlaygroundStory, createWebScenarioStory } from './playground.js';

export default {
  title: 'Components/Label',
};

const componentId = 'label' as const;

export const Playground = createWebPlaygroundStory(componentId);

export const Overview = createWebScenarioStory(componentId, 'overview');

export const Optional = createWebScenarioStory(componentId, 'optional');
