// Generated by packages/storybook-fixtures/scripts/generate-stories.js.
// Do not edit directly. Run `pnpm storybook:stories:generate` after Storybook component changes.

import '@cobalt/components/nav-drawer';
import '@cobalt/components/nav-drawer-item';
import '@cobalt/components/nav-separator';
import { createWebPlaygroundStory, createWebScenarioStory } from './playground.js';

export default {
  title: 'Components/Nav Separator',
};

const componentId = 'navSeparator' as const;

export const Playground = createWebPlaygroundStory(componentId);

export const Overview = createWebScenarioStory(componentId, 'overview');
