// Generated by packages/storybook-fixtures/scripts/generate-stories.js.
// Do not edit directly. Run `pnpm storybook:stories:generate` after Storybook component changes.

import '@cobalt/components/nav-header-bar';
import '@cobalt/components/button';
import '@cobalt/components/button-icon';
import '@cobalt/components/icon';
import '@cobalt/components/input-pill';
import { createWebPlaygroundStory, createWebScenarioStory } from './playground.js';

export default {
  title: 'Components/Nav Header Bar',
};

const componentId = 'navHeaderBar' as const;

export const Playground = createWebPlaygroundStory(componentId);

export const Overview = createWebScenarioStory(componentId, 'overview');
