// Generated by packages/storybook-fixtures/scripts/generate-stories.js.
// Do not edit directly. Run `pnpm storybook:stories:generate` after Storybook component changes.

import '@cobalt/components/nav-rail-bar';
import '@cobalt/components/nav-rail-item';
import '@cobalt/components/icon';
import { createWebPlaygroundStory, createWebScenarioStory } from './playground.js';

export default {
  title: 'Components/Nav Rail Item',
};

const componentId = 'navRailItem' as const;

export const Playground = createWebPlaygroundStory(componentId);

export const Overview = createWebScenarioStory(componentId, 'overview');
