// Generated by packages/storybook-fixtures/scripts/generate-stories.js.
// Do not edit directly. Run `pnpm storybook:stories:generate` after Storybook component changes.

import '@cobalt/components/radio-group';
import '@cobalt/components/radio';
import { createWebPlaygroundStory, createWebStarterOverviewStory } from './playground.js';

export default {
  title: 'Components/Radio Group',
};

const componentId = 'radioGroup' as const;

export const Playground = createWebPlaygroundStory(componentId);

export const Overview = createWebStarterOverviewStory(componentId);
