// Generated by packages/storybook-fixtures/scripts/generate-stories.js.
// Do not edit directly. Run `pnpm storybook:stories:generate` after Storybook component changes.

import { createReactPlaygroundStory, createReactScenarioStory } from './playground.js';

export default {
  title: 'Components/Nav Rail Item',
};

const componentId = 'navRailItem' as const;

export const Playground = createReactPlaygroundStory(componentId);

export const Overview = createReactScenarioStory(componentId, 'overview');
