// Generated by packages/storybook-fixtures/scripts/generate-stories.js.
// Do not edit directly. Run `pnpm storybook:stories:generate` after Storybook component changes.

import { createReactPlaygroundStory, createReactScenarioStory } from './playground.js';

export default {
  title: 'Components/Radio Group',
};

const componentId = 'radioGroup' as const;

export const Playground = createReactPlaygroundStory(componentId);

export const Overview = createReactScenarioStory(componentId, 'overview');

export const WithDisabledOption = createReactScenarioStory(componentId, 'withDisabledOption');
