// Generated by packages/storybook-fixtures/scripts/generate-stories.js.
// Do not edit directly. Run `pnpm storybook:stories:generate` after Storybook component changes.

import { createReactPlaygroundStory, createReactStarterOverviewStory } from './playground.js';

export default {
  title: 'Components/Radio Group',
};

const componentId = 'radioGroup' as const;

export const Playground = createReactPlaygroundStory(componentId);

export const Overview = createReactStarterOverviewStory(componentId);
