// Generated by packages/storybook-fixtures/scripts/generate-stories.js.
// Do not edit directly. Run `pnpm storybook:stories:generate` after Storybook component changes.

import { createAngularPlaygroundStory, createAngularScenarioStory } from './playground.js';

export default {
  title: 'Components/Banner',
};

const componentId = 'banner' as const;

export const Playground = createAngularPlaygroundStory(componentId);

export const Overview = createAngularScenarioStory(componentId, 'overview');

export const LongContent = createAngularScenarioStory(componentId, 'longContent');
