// Generated by packages/storybook-fixtures/scripts/generate-stories.js.
// Do not edit directly. Run `pnpm storybook:stories:generate` after Storybook component changes.

import { createAngularPlaygroundStory, createAngularStarterOverviewStory } from './playground.js';

export default {
  title: 'Components/Checkbox Group',
};

const componentId = 'checkboxGroup' as const;

export const Playground = createAngularPlaygroundStory(componentId);

export const Overview = createAngularStarterOverviewStory(componentId);
