// Generated by packages/storybook-fixtures/scripts/generate-stories.js.
// Do not edit directly. Run `pnpm storybook:stories:generate` after Storybook component changes.

import { createAngularPlaygroundStory, createAngularScenarioStory } from './playground.js';

export default {
  title: 'Components/Checkbox',
};

const componentId = 'checkbox' as const;

export const Playground = createAngularPlaygroundStory(componentId);

export const Overview = createAngularScenarioStory(componentId, 'overview');

export const Checked = createAngularScenarioStory(componentId, 'checked');

export const Disabled = createAngularScenarioStory(componentId, 'disabled');
