// Generated by packages/storybook-fixtures/scripts/generate-stories.js.
// Do not edit directly. Run `pnpm storybook:stories:generate` after Storybook component changes.

import { createAngularPlaygroundStory, createAngularScenarioStory } from './playground.js';

export default {
  title: 'Components/Input Pill',
};

const componentId = 'inputPill' as const;

export const Playground = createAngularPlaygroundStory(componentId);

export const Overview = createAngularScenarioStory(componentId, 'overview');

export const Chat = createAngularScenarioStory(componentId, 'chat');
