// Generated by packages/storybook-fixtures/scripts/generate-stories.js.
// Do not edit directly. Run `pnpm storybook:stories:generate` after Storybook component changes.

import { createVuePlaygroundStory, createVueStarterOverviewStory } from './playground.js';

export default {
  title: 'Components/Checkbox',
};

const componentId = 'checkbox' as const;

export const Playground = createVuePlaygroundStory(componentId);

export const Overview = createVueStarterOverviewStory(componentId);
