// Generated by packages/storybook-fixtures/scripts/generate-stories.js.
// Do not edit directly. Run `pnpm storybook:stories:generate` after Storybook component changes.

import { createVuePlaygroundStory, createVueScenarioStory } from './playground.js';

export default {
  title: 'Components/Checkbox',
};

const componentId = 'checkbox' as const;

export const Playground = createVuePlaygroundStory(componentId);

export const Overview = createVueScenarioStory(componentId, 'overview');

export const Checked = createVueScenarioStory(componentId, 'checked');

export const Disabled = createVueScenarioStory(componentId, 'disabled');
