// Generated by packages/storybook-fixtures/scripts/generate-stories.js.
// Do not edit directly. Run `pnpm storybook:stories:generate` after Storybook component changes.

import { createVuePlaygroundStory, createVueScenarioStory } from './playground.js';

export default {
  title: 'Components/Nav Rail Item',
};

const componentId = 'navRailItem' as const;

export const Playground = createVuePlaygroundStory(componentId);

export const Overview = createVueScenarioStory(componentId, 'overview');
