import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { format, resolveConfig } from 'prettier';
import {
  storybookComponentDefinitions,
  storybookManagedComponentDefinitions,
} from '../src/component-registry.js';
import { storybookOverviewOverrides } from '../src/story-overrides.js';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(scriptDir, '../../..');
const checkMode = process.argv.includes('--check');
const generatedHeader = `// Generated by packages/storybook-fixtures/scripts/generate-stories.js.
// Do not edit directly. Run \`pnpm storybook:stories:generate\` after Storybook component changes.
`;

const frameworkConfigs = [
  {
    id: 'web-components',
    filePath: (definition) =>
      resolve(repoRoot, `packages/components/stories/${definition.componentPath}.stories.ts`),
    imports: (definition) => [
      ...new Set(
        definition.webComponentImports.map(
          (componentPath) => `import '@cobalt/components/${componentPath}';`,
        ),
      ),
      "import { createWebPlaygroundStory, createWebStarterOverviewStory } from './playground.js';",
    ],
    playgroundFactory: 'createWebPlaygroundStory',
    overviewFactory: 'createWebStarterOverviewStory',
  },
  {
    id: 'react',
    filePath: (definition) =>
      resolve(repoRoot, `packages/react/stories/${definition.componentPath}.stories.tsx`),
    imports: () => [
      "import { createReactPlaygroundStory, createReactStarterOverviewStory } from './playground.js';",
    ],
    playgroundFactory: 'createReactPlaygroundStory',
    overviewFactory: 'createReactStarterOverviewStory',
  },
  {
    id: 'vue',
    filePath: (definition) =>
      resolve(repoRoot, `packages/vue/stories/${definition.componentPath}.stories.ts`),
    imports: () => [
      "import { createVuePlaygroundStory, createVueStarterOverviewStory } from './playground.js';",
    ],
    playgroundFactory: 'createVuePlaygroundStory',
    overviewFactory: 'createVueStarterOverviewStory',
  },
  {
    id: 'angular',
    filePath: (definition) =>
      resolve(repoRoot, `packages/angular/stories/${definition.componentPath}.stories.ts`),
    imports: () => [
      "import { createAngularPlaygroundStory, createAngularStarterOverviewStory } from './playground.js';",
    ],
    playgroundFactory: 'createAngularPlaygroundStory',
    overviewFactory: 'createAngularStarterOverviewStory',
  },
];

function renderStoryFile(definition, frameworkConfig) {
  const override = storybookOverviewOverrides[definition.id]?.[frameworkConfig.id];
  const imports = [...frameworkConfig.imports(definition), ...(override?.imports ?? [])];
  const overview =
    override?.overview ??
    `export const Overview = ${frameworkConfig.overviewFactory}(componentId);`;

  return `${generatedHeader}
${imports.join('\n')}

export default {
  title: 'Components/${definition.title}',
};

const componentId = '${definition.id}' as const;

export const Playground = ${frameworkConfig.playgroundFactory}(componentId);

${overview}
`;
}

function renderAngularAliasProxy(definition, outputPath) {
  const sourcePath = resolve(repoRoot, definition.componentSource);
  const modulePath = relative(dirname(outputPath), sourcePath)
    .replace(/\\/g, '/')
    .replace(/\.ts$/, '.js');

  return `${generatedHeader}
export * from '${modulePath.startsWith('.') ? modulePath : `./${modulePath}`}';
`;
}

async function formatFile(outputPath, source) {
  const prettierConfig = (await resolveConfig(outputPath)) ?? {};
  return format(source, {
    ...prettierConfig,
    filepath: outputPath,
  });
}

function isGeneratedStoryFile(value) {
  return value.startsWith(generatedHeader);
}

function ensureManagedStoryFile(outputPath, nextContents) {
  if (!existsSync(outputPath)) {
    return { canWrite: true, changed: true };
  }

  const existing = readFileSync(outputPath, 'utf8');
  if (existing === nextContents) {
    return { canWrite: true, changed: false };
  }

  return {
    canWrite: isGeneratedStoryFile(existing),
    changed: true,
  };
}

async function run() {
  const staleFiles = [];
  const blockedFiles = [];

  for (const definition of storybookManagedComponentDefinitions) {
    for (const frameworkConfig of frameworkConfigs) {
      const outputPath = frameworkConfig.filePath(definition);
      const nextContents = await formatFile(
        outputPath,
        renderStoryFile(definition, frameworkConfig),
      );
      const fileState = ensureManagedStoryFile(outputPath, nextContents);

      if (checkMode) {
        if (!existsSync(outputPath) || readFileSync(outputPath, 'utf8') !== nextContents) {
          staleFiles.push(relative(repoRoot, outputPath));
        }
        continue;
      }

      if (!fileState.canWrite) {
        blockedFiles.push(relative(repoRoot, outputPath));
        continue;
      }

      if (!fileState.changed) {
        continue;
      }

      mkdirSync(dirname(outputPath), { recursive: true });
      writeFileSync(outputPath, nextContents);
    }
  }

  for (const definition of storybookComponentDefinitions) {
    const outputPath = resolve(
      repoRoot,
      `packages/storybook-angular/.storybook/component-aliases/${definition.componentPath}.ts`,
    );
    const nextContents = await formatFile(
      outputPath,
      renderAngularAliasProxy(definition, outputPath),
    );
    const fileState = ensureManagedStoryFile(outputPath, nextContents);

    if (checkMode) {
      if (!existsSync(outputPath) || readFileSync(outputPath, 'utf8') !== nextContents) {
        staleFiles.push(relative(repoRoot, outputPath));
      }
      continue;
    }

    if (!fileState.canWrite) {
      blockedFiles.push(relative(repoRoot, outputPath));
      continue;
    }

    if (!fileState.changed) {
      continue;
    }

    mkdirSync(dirname(outputPath), { recursive: true });
    writeFileSync(outputPath, nextContents);
  }

  if (blockedFiles.length > 0) {
    throw new Error(
      [
        'Refusing to overwrite non-generated Storybook story files:',
        ...blockedFiles.map((file) => `- ${file}`),
        'Delete the file or migrate it manually before re-running pnpm storybook:stories:generate.',
      ].join('\n'),
    );
  }

  if (staleFiles.length > 0) {
    throw new Error(
      [
        'Generated Storybook stories are out of date:',
        ...staleFiles.map((file) => `- ${file}`),
        'Run pnpm storybook:stories:generate.',
      ].join('\n'),
    );
  }
}

await run();
