// Generated by packages/storybook-fixtures/scripts/generate-stories.js.
// Do not edit directly. Run `pnpm storybook:stories:generate` after Storybook component changes.

export * from '../../../components/src/components/checkbox-group/co-checkbox-group.js';
